/**
 * The decisive test of this slice: the AST substituter IS the source-to-source
 * rewrite it replaces.
 *
 * Not "produces a module of the same shape" — produces the same bytes, over
 * the same corpus module, down to the sha256 the architecture ruling quotes.
 * A stage that emits those bytes is provably the same rewrite, which is what
 * lets a hand-written string rewrite be deleted without re-arguing anything it
 * decided.
 *
 * Generality is then proven from the other direction, because byte parity with
 * one application would also be satisfied by hardcoding that application. The
 * synthetic case has a different component name, a different context name and
 * a different directory depth, and it is asserted on shape. A stage that
 * passes both is shaped to the analysis rather than to one corpus.
 *
 * The rest are the refusals. Each one is a shape a substituter could guess at
 * and each guess would ship a page that looks right and resumes the wrong
 * element, so each is a named error with a test of its own.
 */

import { createHash } from 'node:crypto';
import { existsSync, readFileSync, rmSync } from 'node:fs';
import { join, resolve } from 'pathe';
import { describe, expect, it } from 'vitest';

import { analyzeFixture } from '../../src/comptime/index.ts';
import type { Analysis } from '../../src/comptime/types.ts';
import { resolveOptions } from '../src/options.ts';
import { runSubstituteStage, SubstitutionError, substituteModule } from '../src/stages/substitute.ts';
import type {
  MountDeclaration,
  ResolvedOptions,
  ResumabilityOptions,
  SubstitutionResult,
} from '../src/types.ts';

const PLUGIN_ROOT = resolve(import.meta.dirname, '..');
const REPO_ROOT = resolve(PLUGIN_ROOT, '..');
const VERIFY_OUT = join(PLUGIN_ROOT, '.verify-out');

/** The module the reference rewrite already shipped, and its quoted hash. */
const REFERENCE = join(REPO_ROOT, 'demo/src/generated/app.resumable.tsx');
const REFERENCE_SHA = '5e20046fe3194815e6f6082a7d0c0ca957a0b170c8ccc8813bdac9dd4b778207';

/**
 * The reference rewrite's own banner, verbatim. Prose is the consumer's, not
 * the stage's: what this slice has to reproduce is every byte of the module,
 * and the banner is the part of it nothing can derive.
 *
 * Which is why this constant moves whenever the consumer's banner moves, and
 * moves WITH the sha above: the banner is an input to the module's bytes, so
 * the generator, the generated module and this lock are one coordinated edit
 * and any two of them agreeing without the third is a red test rather than a
 * quiet drift.
 *
 * OLD (retired 2026-08-13): the banner naming `demo/build/substitute.mjs` as
 * the generator and reading "the single component the comptime pass proves
 * (docs/coverage/coverage.json, app 1/5)", against sha
 * `5656dcd81a748073792609490e06923111d22d0571f77a546630f7d689bd6931`. Both
 * halves of that sentence had gone stale: the plugin emits this module now,
 * and the pass's verdict for it is app 3/5. The wording it was replaced with
 * is careful about the difference the fraction hides — three components are
 * PROVED, exactly one is RESUMED on the wire — which is the reading
 * `docs/coverage/baseline.md` fixes and this lock quotes rather than restates.
 */
const REFERENCE_BANNER = `// Generated by unplugin-solid-resumability from app/src/app.tsx. Do not edit.
//
// The corpus module with ONE edit a resumability compiler would make: the
// mount point of \`Header\` — the single component this demo RESUMES — no
// longer renders a component. It publishes the live store and claims the
// element already carrying the resumed component, and \`Header\`'s body is not
// in this file at all. The other four components are the corpus's own source,
// unchanged.
//
// The pass's verdict for this module is app 3/5 (docs/coverage/coverage.json),
// and the other two proved components are NOT substituted out. What flips a
// \`MainSection\` or \`Footer\` guard is a store write, and a store write is the
// deferred group's — so their bodies stay where the group renders them the
// ordinary way, and a mount here would ship empty. Three verdicts, one
// resumption: read the fraction as coverage, never as components resumed.
`;

function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/** Options plus the one mount, resolved together, the way a stage reads them. */
function setup(mount: MountDeclaration, overrides: Omit<Partial<ResumabilityOptions>, 'mounts'> = {}) {
  const options = resolveOptions({ root: PLUGIN_ROOT, mounts: [mount], ...overrides });
  return { options, mount: options.mounts[0]! };
}

/** Runs the pass over one mount, so the stage is handed the verdict a build would hand it. */
function verdict(options: ResolvedOptions, sourcePath: string, component: string): Analysis {
  return analyzeFixture(sourcePath, { root: options.corpusRoot, component });
}

/** Asserts the stage refused, and refused under the name the caller expected. */
function refusalFrom(run: () => unknown): SubstitutionError {
  let thrown: unknown;
  try {
    run();
  } catch (error) {
    thrown = error;
  }
  expect(thrown, 'expected a refusal, got none').toBeInstanceOf(SubstitutionError);
  return thrown as SubstitutionError;
}

/** One refused fixture, rewritten as far as the stage will take it. */
function substituteFixture(source: string, component: string, out = 'refused.tsx'): SubstitutionResult {
  const { options, mount } = setup({
    component,
    source,
    expectProvable: false,
    substitute: {
      out,
      claim: { module: 'test/fixtures/corpus/shared/shelf-resume.ts' },
    },
  });
  return substituteModule(options, mount, verdict(options, mount.sourcePath, component));
}

describe('byte parity with the rewrite this stage replaces', () => {
  const { options, mount } = setup(
    {
      component: 'Header',
      source: 'app/src/app.tsx',
      substitute: {
        out: 'app.resumable.tsx',
        claim: { module: 'demo/src/todos-resume.ts' },
        banner: REFERENCE_BANNER,
      },
    },
    { root: REPO_ROOT, generatedDir: 'demo/src/generated' },
  );

  const result = substituteModule(options, mount, verdict(options, mount.sourcePath, 'Header'));

  it('reproduces the shipped module byte for byte', () => {
    expect(sha256(result.code)).toBe(REFERENCE_SHA);
    expect(result.code).toBe(readFileSync(REFERENCE, 'utf8'));
  });

  it('leaves the module it compared against untouched', () => {
    // The anchor only proves equivalence if the reference side is the file it
    // always was: this stage computes, and the test never writes.
    expect(sha256(readFileSync(REFERENCE, 'utf8'))).toBe(REFERENCE_SHA);
  });

  it('makes exactly the three kinds of edit, all of them derived', () => {
    expect(result.edits.map((edit) => edit.kind)).toEqual([
      'reroot-import',
      'reroot-import',
      'remove-component',
      'replace-mount',
    ]);
    expect(result.edits.map((edit) => edit.text)).toEqual([
      '"../../../app/src/todos"',
      '"../../../app/src/filter"',
      '\n\n',
      '{claimHeader(useContext(TodosContext))}',
    ]);
    expect(result.transformed).toBe(false);
  });

  it('derives the glue import from the declaration and the component name', () => {
    expect(mount.substitute).toMatchObject({
      helper: 'claimHeader',
      specifier: '../todos-resume.ts',
      outPath: REFERENCE,
    });
    expect(result.code).toContain('import { claimHeader } from "../todos-resume.ts";');
  });

  it('leaves no trace of the component it removed', () => {
    expect(result.code).not.toContain('function Header');
    expect(result.code).not.toContain('onKeyDown');
    expect(result.code).not.toContain('addTodo(');
  });
});

describe('a corpus that shares nothing with the one this was extracted from', () => {
  const generatedDir = join(VERIFY_OUT, 'generated/deep/nested');
  const source = 'test/fixtures/corpus/features/shelf/shelf-page.tsx';

  const { options, mount } = setup(
    {
      component: 'ShelfToolbar',
      source,
      substitute: {
        out: 'shelf.resumable.tsx',
        claim: { module: 'test/fixtures/corpus/shared/shelf-resume.ts' },
      },
    },
    { artifactDir: join(VERIFY_OUT, 'substitute-artifacts'), generatedDir },
  );

  rmSync(generatedDir, { recursive: true, force: true });
  const analysis = verdict(options, mount.sourcePath, 'ShelfToolbar');
  const report = runSubstituteStage(options, [{ mount, analysis, emittedDir: null }], { log: () => {} });
  const code = report.results[0]!.code;

  it('is provable, or this case proves nothing', () => {
    expect(analysis.status).toBe('provable');
  });

  it('writes the rewritten module where the declaration put it', () => {
    const written = join(generatedDir, 'shelf.resumable.tsx');
    expect(report.results[0]!.path).toBe(written);
    expect(readFileSync(written, 'utf8')).toBe(code);
  });

  it('removes the component and keeps its siblings', () => {
    expect(code).not.toContain('function ShelfToolbar');
    expect(code).not.toContain('shelveBook');
    expect(code).toContain('export function ShelfPage()');
    expect(code).toContain('<section class="shelf">');
  });

  it('synthesizes the claim expression with this corpus own context name', () => {
    expect(code).toContain('{claimShelfToolbar(useContext(ShelfContext))}');
    expect(code).not.toContain('<ShelfToolbar />');
  });

  it('re-roots the imports to the directory the rewritten module sits in', () => {
    expect(code).toContain('from "../../../../test/fixtures/corpus/shared/shelf-store"');
    expect(code).toContain(
      'import { claimShelfToolbar } from "../../../../test/fixtures/corpus/shared/shelf-resume.ts";',
    );
    // A specifier nobody has to resolve from disk is left as written.
    expect(code).toContain('from "solid-js"');
  });

  it('opens with a provenance note when the declaration supplies no prose', () => {
    expect(code.startsWith(`// Generated by unplugin-solid-resumability from ${source}.`)).toBe(true);
  });

  it('is deterministic: a second run writes the same bytes', () => {
    const again = runSubstituteStage(options, [{ mount, analysis, emittedDir: null }], { log: () => {} });
    expect(again.results[0]!.code).toBe(code);
  });
});

describe('the shapes it refuses rather than guesses at', () => {
  it('refuses a mount point carrying props or children', () => {
    const error = refusalFrom(() =>
      substituteFixture('test/fixtures/corpus/refusals/propped-mount.tsx', 'CrateToolbar'),
    );
    expect(error.name).toBe('MountElementNotBare');
    expect(error.message).toContain('CrateToolbar');
    expect(error.message).toContain('1 prop(s)');
    expect(error.message).toContain('artifacts model neither');
  });

  it('refuses a component mounted more than once', () => {
    const error = refusalFrom(() =>
      substituteFixture('test/fixtures/corpus/refusals/twice-mounted.tsx', 'CaseToolbar'),
    );
    expect(error.name).toBe('MultipleMountSites');
    expect(error.message).toContain('mounts `CaseToolbar` 2 times');
    expect(error.message).toContain('is not decidable');
  });

  it('refuses a context the mount module knows under another name', () => {
    const error = refusalFrom(() =>
      substituteFixture('test/fixtures/corpus/refusals/aliased-context.tsx', 'AisleToolbar'),
    );
    expect(error.name).toBe('ContextBindingUnreachable');
    expect(error.message).toContain('`AisleContext`');
    expect(error.message).toContain('test/fixtures/corpus/refusals/aisle-context.ts');
    expect(error.message).toContain('`Aisle`');
  });

  it('refuses a component declared in a module other than the one mounting it', () => {
    const error = refusalFrom(() =>
      substituteFixture('test/fixtures/corpus/refusals/remote-mount.tsx', 'DepotToolbar'),
    );
    expect(error.name).toBe('ComponentNotModuleLocal');
    expect(error.message).toContain('mounts `DepotToolbar` but does not declare it');
    expect(error.message).toContain('same');
  });

  it('refuses a component the pass could not prove', () => {
    const error = refusalFrom(() =>
      substituteFixture('test/fixtures/refusal/EscapingCounter.tsx', 'EscapingCounter'),
    );
    expect(error.name).toBe('UnprovableSubstitution');
    expect(error.message).toContain('classified fallback');
    expect(error.message).toContain('no artifacts');
  });

  it('refuses a mount that declares no glue to claim with', () => {
    let thrown: unknown;
    try {
      resolveOptions({
        root: PLUGIN_ROOT,
        mounts: [
          {
            component: 'ShelfToolbar',
            source: 'test/fixtures/corpus/features/shelf/shelf-page.tsx',
            substitute: { out: 'shelf.resumable.tsx', claim: { module: '' } },
          },
        ],
      });
    } catch (error) {
      thrown = error;
    }
    expect((thrown as Error).name).toBe('ClaimGlueUndeclared');
  });
});

describe('the escape hatch, for shapes the analysis refuses', () => {
  const REPLACEMENT = '// hand-written by the consumer\nexport function Page() {}\n';

  it('is handed the refusal, and its output is used verbatim', () => {
    const outPath = join(VERIFY_OUT, 'generated/hatch/refused.tsx');
    rmSync(outPath, { force: true });

    const source = 'test/fixtures/corpus/refusals/propped-mount.tsx';
    const options = resolveOptions({
      root: PLUGIN_ROOT,
      generatedDir: join(VERIFY_OUT, 'generated/hatch'),
      mounts: [
        {
          component: 'CrateToolbar',
          source,
          expectProvable: false,
          substitute: {
            out: 'refused.tsx',
            claim: { module: 'test/fixtures/corpus/shared/shelf-resume.ts' },
          },
        },
      ],
      substitute: {
        transform: (context) => {
          expect(context.path).toBe(join(PLUGIN_ROOT, source));
          expect(context.outPath).toBe(outPath);
          expect(context.mount.component).toBe('CrateToolbar');
          expect(context.source).toContain('<CrateToolbar tone="quiet" />');
          expect(context.analysis.status).toBe('provable');
          expect(context.refusal?.name).toBe('MountElementNotBare');
          expect(context.edits).toEqual([]);
          return REPLACEMENT;
        },
      },
    });

    const mount = options.mounts[0]!;
    const analysis = verdict(options, mount.sourcePath, 'CrateToolbar');
    const report = runSubstituteStage(options, [{ mount, analysis, emittedDir: null }], {
      log: () => {},
    });

    expect(report.results[0]!.transformed).toBe(true);
    expect(report.results[0]!.code).toBe(REPLACEMENT);
    expect(existsSync(outPath)).toBe(true);
    expect(readFileSync(outPath, 'utf8')).toBe(REPLACEMENT);
  });

  it('wins over a rewrite the stage could have made itself, and sees its edits', () => {
    const source = 'test/fixtures/corpus/features/shelf/shelf-page.tsx';
    let seen: string[] = [];

    const options = resolveOptions({
      root: PLUGIN_ROOT,
      generatedDir: join(VERIFY_OUT, 'generated/hatch'),
      mounts: [
        {
          component: 'ShelfToolbar',
          source,
          substitute: {
            out: 'accepted.tsx',
            claim: { module: 'test/fixtures/corpus/shared/shelf-resume.ts' },
          },
        },
      ],
      substitute: {
        transform: (context) => {
          seen = context.edits.map((edit) => edit.kind);
          expect(context.refusal).toBeUndefined();
          return REPLACEMENT;
        },
      },
    });

    const mount = options.mounts[0]!;
    const result = substituteModule(options, mount, verdict(options, mount.sourcePath, 'ShelfToolbar'));

    expect(seen).toEqual(['reroot-import', 'remove-component', 'replace-mount']);
    expect(result.code).toBe(REPLACEMENT);
  });
});

describe('a claim module nobody has to resolve from disk', () => {
  it('is emitted exactly as it was declared', () => {
    const { mount } = setup({
      component: 'ShelfToolbar',
      source: 'test/fixtures/corpus/features/shelf/shelf-page.tsx',
      substitute: {
        out: 'shelf.resumable.tsx',
        claim: { helper: 'resumeToolbar', module: '@acme/glue/resume' },
      },
    });

    expect(mount.substitute).toMatchObject({
      helper: 'resumeToolbar',
      specifier: '@acme/glue/resume',
    });
  });
});
