// Generated by the solid-resumability comptime pass. Do not edit.
// Source: app/src/fixtures/KeyedRoster.tsx -> RosterList

/** Source cells: one per `createSignal(<literal>)` proven local to the component. */
export const cells = [
  { id: "c0", initial: "none", getter: "last", setter: "setLast" },
];

/**
 * Context-provided stores this component takes its actions from. Identity
 * only: the context that names the store and the provider proven to supply it.
 * The store's value — its data, its projection, its optimistic overlay — is
 * runtime state this pass deliberately says nothing about.
 */
export const stores = [
  {
    id: "s0",
    context: "RosterContext",
    contextModule: "app/src/fixtures/KeyedRoster.tsx",
    actionsSlot: 1,
    readSlot: 0,
    provider: "app/src/fixtures/KeyedRoster.tsx",
    value: { module: "app/src/fixtures/roster.ts", factory: "createRoster" },
  },
];

/**
 * Store actions, by identity. `path` is the fixed slot path from the
 * provider's value that reaches the action; no action body was read to produce
 * this, and none is shipped in these artifacts.
 */
export const actions = [
  { id: "s0a0", store: "s0", name: "drop", path: [1,"drop"] },
];

/** Store data this component reads, by identity. Reads only: nothing here
 * writes, and no value was frozen. */
export const reads = [
  { id: "s0r", store: "s0", name: "roster", path: [0] },
];

/**
 * Cell -> DOM bindings. A "text" binding owns the `textContent` of the
 * element at `locator`; `compute` re-derives that text from the cells named
 * in `captures`, and `initialText` is that derivation folded at build time.
 */
export const bindings = [
  {
    id: "b0",
    kind: "text",
    locator: "/0",
    initialText: "none",
    captures: [
      { name: "last", cell: "c0", access: "read" },
    ],
    // Derivation, printed from the component's own source.
    compute({ last }) {
      return last();
    },
  },
];

/**
 * Keyed `<For>` regions. The resume path never BUILDS one of these lists — it
 * READS the one the served markup already carries: walk the container's
 * children, take each element's key off `keyAttribute`, and resolve an item's
 * binding or listener from that element. A key the markup does not carry refuses
 * loudly rather than binding to a neighbour, which is the whole of why this is
 * an identity and not an index.
 */
export const keyedRegions = [
  {
    id: "k0",
    container: "/1",
    item: "member",
    keyAttribute: "data-key",
    keyPath: ["id"],
    itemTemplate: "<li class=\"member\" data-key=\"\"><span class=\"name\"></span><button class=\"drop\">x</button></li>",
    captures: [
      { name: "roster", kind: "store-read", store: "s0", path: [0] },
    ],
    // The list projection, printed from the component's own source. Evaluated
    // against the LIVE store, never here: at build time there is no list.
    each({ roster }) {
      return roster.members;
    },
    // Addressed from the ITEM element, not from the component's root.
    bindings: [
      {
        id: "k0b0",
        kind: "text",
        locator: "/0",
        initialText: "",
        // Measured from the page's captured first paint, not derived.
        initialTextFrom: "capture",
        captures: [
          { name: "member", kind: "region-item", region: "k0" },
        ],
        // Derivation, printed from the component's own source.
        compute({ member }) {
          return member.name;
        },
      },
    ],
    wiring: [
      {
        locator: "/1",
        event: "click",
        module: "./handlers/s0.js",
        handler: "s0",
        captures: [
          { name: "drop", kind: "action", store: "s0", path: [1,"drop"] },
          { name: "member", kind: "region-item", region: "k0" },
          { name: "setLast", cell: "c0", access: "write" },
        ],
      },
    ],
  },
];
