// Generated by the solid-resumability comptime pass. Do not edit.
// Source: app/src/app.tsx -> MainSection

/** Source cells: one per `createSignal(<literal>)` proven local to the component. */
export const cells = [

];

/**
 * Context-provided stores this component takes its actions from. Identity
 * only: the context that names the store and the provider proven to supply it.
 * The store's value — its data, its projection, its optimistic overlay — is
 * runtime state this pass deliberately says nothing about.
 */
export const stores = [
  {
    id: "s0",
    context: "TodosContext",
    contextModule: "app/src/app.tsx",
    actionsSlot: 1,
    readSlot: 0,
    provider: "app/src/app.tsx",
    value: { module: "app/src/todos.ts", factory: "createTodos" },
  },
];

/**
 * Store actions, by identity. `path` is the fixed slot path from the
 * provider's value that reaches the action; no action body was read to produce
 * this, and none is shipped in these artifacts.
 */
export const actions = [
  { id: "s0a0", store: "s0", name: "toggleAll", path: [1,"toggleAll"] },
];

/** Store data this component reads, by identity. Reads only: nothing here
 * writes, and no value was frozen. */
export const reads = [
  { id: "s0r", store: "s0", name: "todos", path: [0] },
];

/**
 * Cell -> DOM bindings. A "text" binding owns the `textContent` of the
 * element at `locator`; `compute` re-derives that text from the cells named
 * in `captures`, and `initialText` is that derivation folded at build time.
 */
export const bindings = [

];

/**
 * Two-state `<Show>` regions, each in the state this build recorded. A region
 * is a guard, not a toggle: an absent one has no DOM here, owns no binding and
 * no wiring, and nothing on the resume path creates it.
 */
export const regions = [
  {
    id: "r0",
    locator: "/",
    present: false,
    // The guard reaches into a store, so the build could not fold it: the region
    // is recorded absent and the page's captured first paint is what proves it.
    presentFrom: "capture",
    captures: [
      { name: "todos", kind: "store-read", store: "s0", path: [0] },
    ],
    when({ todos }) {
      return todos.length > 0;
    },
  },
];
