// Generated by the solid-resumability comptime pass. Do not edit.
// Source: app/src/app.tsx -> MainSection

/**
 * The component's markup at its cells' initial values — byte-for-byte what an
 * unmodified `render()` of this component produces before any interaction.
 * `test/parity.test.tsx` is the proof.
 */
export const html = "";

/**
 * Locators address nodes by child index from the component's root element:
 * "/" is the root, "/1" its second element child, "/1/0" that child's first.
 * The template contains no whitespace-only text nodes, so these indices hold
 * for `childNodes` as well as `children`.
 */
export const root = "/";
