// Generated by the solid-resumability comptime pass. Do not edit.
// Source: app/src/app.tsx -> MainSection

/**
 * Wiring records: which element gets which listener, and where the handler's
 * code lives. `module` is relative to this file so it can be `import()`ed
 * lazily — the whole point being that none of it loads until the event fires.
 */
export const wiring = [

];
