// Generated by the solid-resumability comptime pass. Do not edit.
// Source: src/fixtures/CounterA.tsx -> CounterA

/** Source cells: one per `createSignal(<literal>)` proven local to the component. */
export const cells = [
  { id: "c0", initial: 0, getter: "count", setter: "setCount" },
];

/**
 * Cell -> DOM bindings. A "text" binding owns the `textContent` of the
 * element at `locator`; `compute` re-derives that text from the cells named
 * in `captures`, and `initialText` is that derivation folded at build time.
 */
export const bindings = [
  {
    id: "b0",
    kind: "text",
    locator: "/0",
    initialText: "count: 0",
    captures: [
      { name: "count", cell: "c0", access: "read" },
    ],
    // Derivation, printed from the component's own source.
    compute({ count }) {
      return "count: " + count();
    },
  },
];
