// Generated by the solid-resumability comptime pass. Do not edit.
// Source: src/fixtures/CounterA.tsx -> CounterA

/**
 * Wiring records: which element gets which listener, and where the handler's
 * code lives. `module` is relative to this file so it can be `import()`ed
 * lazily — the whole point being that none of it loads until the event fires.
 */
export const wiring = [
  {
    locator: "/1",
    event: "click",
    module: "./handlers/s0.js",
    handler: "s0",
    captures: [
      { name: "count", cell: "c0", access: "read" },
      { name: "setCount", cell: "c0", access: "write" },
    ],
  },
  {
    locator: "/2",
    event: "click",
    module: "./handlers/s1.js",
    handler: "s1",
    captures: [
      { name: "count", cell: "c0", access: "read" },
      { name: "setCount", cell: "c0", access: "write" },
    ],
  },
];
