/**
 * The emitter: a provable analysis in, four kinds of static ES module out, all
 * plain data or plain functions with no imports of their own.
 *
 *   template.js   the markup at initial state, as one HTML string
 *   structure.js  source cells and cell -> DOM text bindings
 *   handlers/*.js one lazily-importable module per event handler, factored over
 *                 an explicit capture-slot manifest
 *   wiring.js     DOM locator + event -> handler module + capture slots
 *
 * Emission is deterministic: no timestamps, no absolute paths, no hashes of
 * anything but the analysis, every collection written in a fixed order.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, relative } from "pathe";

import {
  isActionSlot,
  isIdentitySlot,
  isRegionItemSlot,
  isStoreReadSlot,
  type BindingInfo,
  type CaptureSlot,
  type CodeOrigin,
  type EmitResult,
  type HandlerOrigin,
  type InitialFrom,
  type ProvableAnalysis,
} from "./types.ts";

const BANNER = "// Generated by the solid-resumability comptime pass. Do not edit.";

function js(value: unknown): string {
  return JSON.stringify(value);
}

/**
 * One capture-slot line. The cell arm's emitted form is byte-frozen. The action
 * and store-read arms carry no cell — a store id and the fixed slot path
 * reaching the action, or the store's own data, is the whole of what the pass
 * proved.
 */
function slotLine(slot: CaptureSlot, indent: string): string {
  if (isActionSlot(slot)) {
    return `${indent}  { name: ${js(slot.name)}, kind: "action", store: ${js(slot.store)}, path: ${js(slot.path)} },`;
  }
  if (isStoreReadSlot(slot)) {
    return `${indent}  { name: ${js(slot.name)}, kind: "store-read", store: ${js(slot.store)}, path: ${js(slot.path)} },`;
  }
  if (isRegionItemSlot(slot)) {
    return `${indent}  { name: ${js(slot.name)}, kind: "region-item", region: ${js(slot.region)} },`;
  }
  if (isIdentitySlot(slot)) {
    return `${indent}  { name: ${js(slot.name)}, kind: "identity", bindingClass: ${js(slot.bindingClass)}, source: ${js(slot.source)} },`;
  }
  return `${indent}  { name: ${js(slot.name)}, cell: ${js(slot.cell)}, access: ${js(slot.access)} },`;
}

function slotList(slots: CaptureSlot[], indent: string): string {
  if (slots.length === 0) return "[]";
  const inner = slots.map((slot) => slotLine(slot, indent)).join("\n");
  return `[\n${inner}\n${indent}]`;
}

/** `{ count, setCount }` — the destructuring pattern a capture manifest implies. */
function slotPattern(slots: CaptureSlot[]): string {
  if (slots.length === 0) return "_slots";
  return `{ ${slots.map((slot) => slot.name).join(", ")} }`;
}

function header(analysis: ProvableAnalysis): string {
  return `${BANNER}\n// Source: ${analysis.module} -> ${analysis.component}\n`;
}

/** A see-through parent's template reproduces Solid's `<!---->` placeholders, so
 * its `childNodes` are wider than its `children`. Locators are ELEMENT indices,
 * which comment nodes cannot shift, so resolution is unchanged — but the artifact
 * must not claim the stronger fact. Placeholder-free templates keep the original
 * wording byte for byte. */
function locatorNote(analysis: ProvableAnalysis): string {
  if (!analysis.html.includes("<!---->")) {
    return ` * The template contains no whitespace-only text nodes, so these indices hold
 * for \`childNodes\` as well as \`children\`.`;
  }
  return ` * The template contains no whitespace-only text nodes, but it does carry the
 * \`<!---->\` placeholders Solid renders after a component child, so these
 * indices are \`children\` indices — which comment nodes cannot shift — and
 * not \`childNodes\` indices.`;
}

function emitTemplate(analysis: ProvableAnalysis): string {
  return `${header(analysis)}
/**
 * The component's markup at its cells' initial values — byte-for-byte what an
 * unmodified \`render()\` of this component produces before any interaction.
 * \`test/parity.test.tsx\` is the proof.
 */
export const html = ${js(analysis.html)};

/**
 * Locators address nodes by child index from the component's root element:
 * "/" is the root, "/1" its second element child, "/1/0" that child's first.
${locatorNote(analysis)}
 */
export const root = "/";
`;
}

/** One line of provenance above each `compute`, keyed by where its source came from. */
const BINDING_DOC: Record<CodeOrigin, string> = {
  component: "// Derivation, printed from the component's own source.",
  helper: "// Derivation, folded through a pure helper this pass summarized.",
  child: "// Derivation, folded out of a child component this pass inlined at this locator.",
};

/**
 * The `initialTextFrom` line, emitted only for a binding whose text is measured.
 * A derivation-sourced binding writes nothing, so every artifact from before
 * store reads comes out byte for byte what it was — the same discipline
 * `emitStores` follows, and what keeps the golden templates golden.
 *
 * `initialText` is empty above this line and stays empty until a build measures
 * it: the prerender stage reads this binding's element out of the captured first
 * paint and writes the text back in, which is the only honest source for a value
 * that lives in a store the build never ran.
 */
function measuredNote(field: string, from: InitialFrom): string {
  if (from !== "capture") return "";
  return `\n    // Measured from the page's captured first paint, not derived.\n    ${field}: "capture",`;
}

/**
 * The other two kinds, described only where they occur. Same discipline as
 * `emitStores`: an artifact says nothing about what it does not contain, so
 * every structure module emitted before these kinds existed still comes out byte
 * for byte what it was.
 */
function bindingKindsNote(analysis: ProvableAnalysis): string {
  const kinds = new Set(analysis.bindings.map((binding) => binding.kind));
  const lines: string[] = [];
  if (kinds.has("attribute")) {
    lines.push(
      ` * An "attribute" binding owns ONE attribute of its element the same way. A`,
      ` * \`property\` one is DOM state markup cannot carry — \`input.checked\` is not`,
      ` * the \`checked\` attribute — so it is assigned rather than set.`,
    );
  }
  if (kinds.has("class")) {
    lines.push(
      ` * A "class" binding owns a NAMED SET of class names, never the whole`,
      ` * attribute: a class the page put on this element by other means is not in`,
      ` * the record, and is not this binding's to remove.`,
    );
  }
  return lines.length === 0 ? "" : `\n${lines.join("\n")}`;
}

/** Shifts an already-rendered block right, so a binding nested inside a region
 * is written by the same function that writes a top-level one rather than by a
 * second one that would have to agree with it. */
function padBlock(block: string, pad: string): string {
  return block
    .split("\n")
    .map((line) => (line === "" ? line : pad + line))
    .join("\n");
}

/** One binding, in the shape its kind needs. Every arm carries `id`, `kind`,
 * `locator` and `captures` in that order, so the three read as one format with
 * three endings rather than three formats. */
function emitBinding(binding: BindingInfo): string {
  const head = `  {
    id: ${js(binding.id)},
    kind: ${js(binding.kind)},
    locator: ${js(binding.locator)},`;

  if (binding.kind === "attribute") {
    return `${head}
    attribute: ${js(binding.attribute)},${binding.property ? "\n    // DOM state, not markup: assigned rather than set as an attribute.\n    property: true," : ""}
    initialValue: ${js(binding.initialValue)},${measuredNote("initialValueFrom", binding.initialValueFrom)}
    captures: ${slotList(binding.captures, "    ")},
    ${BINDING_DOC[binding.origin]}
    compute(${slotPattern(binding.captures)}) {
      return ${binding.expression};
    },
  },`;
  }

  if (binding.kind === "class") {
    const classes = binding.conditions
      .map(
        (condition) => `      {
        name: ${js(condition.name)},
        initial: ${js(condition.initial)},
        compute(${slotPattern(binding.captures)}) {
          return ${condition.expression};
        },
      },`,
      )
      .join("\n");

    return `${head}${measuredNote("initialFrom", binding.initialFrom)}
    captures: ${slotList(binding.captures, "    ")},
    ${BINDING_DOC[binding.origin]}
    classes: [
${classes}
    ],
  },`;
  }

  return `${head}
    initialText: ${js(binding.initialText)},${measuredNote("initialTextFrom", binding.initialTextFrom)}
    captures: ${slotList(binding.captures, "    ")},
    ${BINDING_DOC[binding.origin]}
    compute(${slotPattern(binding.captures)}) {
      return ${binding.expression};
    },
  },`;
}

function emitStructure(analysis: ProvableAnalysis): string {
  const cells = analysis.cells
    .map(
      (cell) =>
        `  { id: ${js(cell.id)}, initial: ${js(cell.initial)}, getter: ${js(cell.getter)}, setter: ${js(cell.setter)} },`,
    )
    .join("\n");

  const bindings = analysis.bindings.map(emitBinding).join("\n");

  return `${header(analysis)}
/** Source cells: one per \`createSignal(<literal>)\` proven local to the component. */
export const cells = [
${cells}
];
${emitStores(analysis)}
/**
 * Cell -> DOM bindings. A "text" binding owns the \`textContent\` of the
 * element at \`locator\`; \`compute\` re-derives that text from the cells named
 * in \`captures\`, and \`initialText\` is that derivation folded at build time.${bindingKindsNote(analysis)}
 */
export const bindings = [
${bindings}
];
${emitRegions(analysis)}${emitKeyedRegions(analysis)}`;
}

/**
 * The keyed regions, emitted only for a component that has one — the same
 * discipline every other optional export here follows, so an artifact from
 * before `<For>` was admitted comes out byte for byte what it was.
 *
 * What travels is a way to READ a list, never a way to build one. `container` is
 * the element whose children ARE the items; `keyAttribute` is where each item
 * carries its key; `itemTemplate` is one item's markup with locators rooted at
 * the item element. `each` is the author's own projection, factored over the
 * same capture slots everything else uses — the resume path calls it to answer
 * "which item is key K", and for nothing else, because a region's DOM is
 * read-only until the group takes over.
 */
function emitKeyedRegions(analysis: ProvableAnalysis): string {
  if (analysis.keyedRegions.length === 0) return "";

  const emitted = analysis.keyedRegions
    .map(
      (region) => `  {
    id: ${js(region.id)},
    container: ${js(region.container)},
    item: ${js(region.item)},
    keyAttribute: ${js(region.keyAttribute)},
    keyPath: ${js(region.keyPath)},
    itemTemplate: ${js(region.itemTemplate)},
    captures: ${slotList(region.captures, "    ")},
    // The list projection, printed from the component's own source. Evaluated
    // against the LIVE store, never here: at build time there is no list.
    each(${slotPattern(region.captures)}) {
      return ${region.each};
    },
    // Addressed from the ITEM element, not from the component's root.
    bindings: [
${region.itemBindings.map((binding) => padBlock(emitBinding(binding), "    ")).join("\n")}
    ],
    wiring: [
${region.itemWiring
  .map(
    (record) => `      {
        locator: ${js(record.locator)},
        event: ${js(record.event)},
        module: ${js(record.module)},
        handler: ${js(record.handler)},
        captures: ${slotList(record.captures, "        ")},
      },`,
  )
  .join("\n")}
    ],
  },`,
    )
    .join("\n");

  return `
/**
 * Keyed \`<For>\` regions. The resume path never BUILDS one of these lists — it
 * READS the one the served markup already carries: walk the container's
 * children, take each element's key off \`keyAttribute\`, and resolve an item's
 * binding or listener from that element. A key the markup does not carry refuses
 * loudly rather than binding to a neighbour, which is the whole of why this is
 * an identity and not an index.
 */
export const keyedRegions = [
${emitted}
];
`;
}

/**
 * The two-state regions, emitted only for a component that has one — the same
 * discipline `emitStores` follows, so every artifact from before control flow
 * comes out byte for byte what it was.
 *
 * A region is a GUARD. `present: false` says this page's markup does not carry
 * the region at all, and nothing on the resume path builds it: the write that
 * would flip the guard belongs to the store, the store belongs to the group, and
 * the group renders the component the ordinary way. `when` travels anyway, so a
 * page can ask what the guard says — it is a claim about the markup, never an
 * instruction to change it.
 */
function emitRegions(analysis: ProvableAnalysis): string {
  if (analysis.regions.length === 0) return "";

  const regions = analysis.regions
    .map(
      (region) => `  {
    id: ${js(region.id)},
    locator: ${js(region.locator)},
    present: ${js(region.present)},${
      region.presentFrom === "capture"
        ? "\n    // The guard reaches into a store, so the build could not fold it: the region\n    // is recorded absent and the page's captured first paint is what proves it.\n    presentFrom: \"capture\","
        : ""
    }
    captures: ${slotList(region.captures, "    ")},
    when(${slotPattern(region.captures)}) {
      return ${region.when};
    },
  },`,
    )
    .join("\n");

  return `
/**
 * Two-state \`<Show>\` regions, each in the state this build recorded. A region
 * is a guard, not a toggle: an absent one has no DOM here, owns no binding and
 * no wiring, and nothing on the resume path creates it.
 */
export const regions = [
${regions}
];
`;
}

/**
 * The store half of `structure.js`, emitted only for a component that has one so
 * every pre-S3 artifact still comes out byte for byte. No initial value, ever: a
 * store's data is an async projection under an optimistic overlay, and a frozen
 * snapshot would be a claim the analysis cannot make. Identity is written
 * instead, so a resume can look the live store up and dispatch to it.
 */
function emitStores(analysis: ProvableAnalysis): string {
  if (analysis.stores.length === 0) return "";

  const stores = analysis.stores
    .map(
      (store) => `  {
    id: ${js(store.id)},
    context: ${js(store.context)},
    contextModule: ${js(store.contextModule)},
    actionsSlot: ${js(store.actionsSlot)},
    readSlot: ${js(store.readSlot)},
    provider: ${js(store.provider.module)},
    value: { module: ${js(store.value.module)}, factory: ${js(store.value.factory)} },
  },`,
    )
    .join("\n");

  const actions = analysis.actions
    .map(
      (action) =>
        `  { id: ${js(action.id)}, store: ${js(action.store)}, name: ${js(action.name)}, path: ${js(action.path)} },`,
    )
    .join("\n");

  return `
/**
 * Context-provided stores this component takes its actions from. Identity
 * only: the context that names the store and the provider proven to supply it.
 * The store's value — its data, its projection, its optimistic overlay — is
 * runtime state this pass deliberately says nothing about.
 */
export const stores = [
${stores}
];

/**
 * Store actions, by identity. \`path\` is the fixed slot path from the
 * provider's value that reaches the action; no action body was read to produce
 * this, and none is shipped in these artifacts.
 */
export const actions = [
${actions}
];
${emitReads(analysis)}`;
}

/**
 * The store's data, by identity, emitted only for a component that binds it.
 * `path` reaches the slot and stops: what the data contains is not here, was not
 * read, and cannot be, because it does not exist until the page runs. A binding
 * that derives text through one of these carries the same `{ store, path }` in
 * its capture manifest and its own expression on top.
 */
function emitReads(analysis: ProvableAnalysis): string {
  if (analysis.reads.length === 0) return "";

  const reads = analysis.reads
    .map(
      (read) =>
        `  { id: ${js(read.id)}, store: ${js(read.store)}, name: ${js(read.name)}, path: ${js(read.path)} },`,
    )
    .join("\n");

  return `
/** Store data this component reads, by identity. Reads only: nothing here
 * writes, and no value was frozen. */
export const reads = [
${reads}
];
`;
}

const OWN_HANDLER_DOC = `/**
 * One event handler, extracted whole from the component and factored over an
 * explicit capture-slot manifest. The function body below is the author's
 * own source, printed back out by yuku-codegen; nothing was injected into the
 * component to make this possible.
 */`;

/** The same, for a handler that was never written in the markup: the closure a
 * summarized factory returns, with the factory's parameters as slot names. */
const FACTORED_HANDLER_DOC = `/**
 * One event handler, taken from the closure a pure factory returns and
 * factored over an explicit capture-slot manifest. The function body below is
 * the helper's own source, printed back out by yuku-codegen; the slot names
 * are its parameters, each bound to the cell the component passed for it.
 */`;

/** And for the one handler with no code in it: the markup handed a store action
 * straight to an event prop, so there is nothing to factor and nothing to
 * print. `create` hands back the slot itself. */
const ACTION_HANDLER_DOC = `/**
 * One event handler that IS a store action. Nobody wrote this listener: the
 * markup named an action, this pass admitted that action by identity — its
 * store and the fixed slot path reaching it — and never read its body. What
 * \`create\` returns is the live store's own function at that path, called with
 * the event exactly as the framework would have called it.
 */`;

const HANDLER_DOC: Record<HandlerOrigin, string> = {
  component: OWN_HANDLER_DOC,
  helper: FACTORED_HANDLER_DOC,
  action: ACTION_HANDLER_DOC,
};

function emitHandler(analysis: ProvableAnalysis, index: number): string {
  const handler = analysis.handlers[index];
  return `${header(analysis)}
${HANDLER_DOC[handler.origin]}
export const id = ${js(handler.id)};
export const event = ${js(handler.event)};
export const locator = ${js(handler.locator)};

/** The slots \`create\` needs, and the cell each one is bound to. */
export const captures = ${slotList(handler.captures, "")};

export function create(${slotPattern(handler.captures)}) {
  return ${handler.source};
}
`;
}

function emitWiring(analysis: ProvableAnalysis): string {
  const records = analysis.wiring
    .map(
      (record) => `  {
    locator: ${js(record.locator)},
    event: ${js(record.event)},
    module: ${js(record.module)},
    handler: ${js(record.handler)},
    captures: ${slotList(record.captures, "    ")},
  },`,
    )
    .join("\n");

  return `${header(analysis)}
/**
 * Wiring records: which element gets which listener, and where the handler's
 * code lives. \`module\` is relative to this file so it can be \`import()\`ed
 * lazily — the whole point being that none of it loads until the event fires.
 */
export const wiring = [
${records}
];
`;
}

function emitManifest(analysis: ProvableAnalysis, files: string[]): string {
  return (
    JSON.stringify(
      {
        component: analysis.component,
        module: analysis.module,
        status: analysis.status,
        cells: analysis.cells.map((cell) => ({
          id: cell.id,
          initial: cell.initial,
          getter: cell.getter,
          setter: cell.setter,
        })),
        // Present only for a component that has one. A key with an empty array
        // in it would rewrite every artifact emitted before this slice, and
        // "nothing changed" has to stay literally true.
        ...(analysis.stores.length === 0
          ? {}
          : {
              stores: analysis.stores.map((store) => ({
                id: store.id,
                context: store.context,
                contextModule: store.contextModule,
                actionsSlot: store.actionsSlot,
                readSlot: store.readSlot,
                provider: store.provider.module,
                value: store.value,
              })),
              actions: analysis.actions.map((action) => ({
                id: action.id,
                store: action.store,
                name: action.name,
                path: action.path,
              })),
              // Same rule one level down: a store with no read binding writes no
              // `reads` key, so an S3 manifest is unchanged by this slice.
              ...(analysis.reads.length === 0
                ? {}
                : {
                    reads: analysis.reads.map((read) => ({
                      id: read.id,
                      store: read.store,
                      name: read.name,
                      path: read.path,
                    })),
                  }),
            }),
        bindings: analysis.bindings.map((binding) => {
          const common = {
            id: binding.id,
            kind: binding.kind,
            locator: binding.locator,
            captures: binding.captures,
          };
          if (binding.kind === "attribute") {
            return {
              ...common,
              attribute: binding.attribute,
              ...(binding.property ? { property: true } : {}),
              expression: binding.expression,
              initialValue: binding.initialValue,
              ...(binding.initialValueFrom === "capture" ? { initialValueFrom: "capture" } : {}),
            };
          }
          if (binding.kind === "class") {
            return {
              ...common,
              statics: binding.statics,
              conditions: binding.conditions,
              ...(binding.initialFrom === "capture" ? { initialFrom: "capture" } : {}),
            };
          }
          return {
            ...common,
            expression: binding.expression,
            initialText: binding.initialText,
            // Written only where it is not the default, for the same reason.
            ...(binding.initialTextFrom === "capture" ? { initialTextFrom: "capture" } : {}),
          };
        }),
        // Same rule as `stores`: a component with no control flow writes no
        // `regions` key, so every manifest emitted before regions existed is
        // unchanged by their existence.
        ...(analysis.regions.length === 0
          ? {}
          : {
              regions: analysis.regions.map((region) => ({
                id: region.id,
                locator: region.locator,
                when: region.when,
                present: region.present,
                ...(region.presentFrom === "capture" ? { presentFrom: "capture" } : {}),
                captures: region.captures,
              })),
            }),
        // Same rule again: a component with no list writes no `keyedRegions`
        // key, so every manifest emitted before `<For>` was admitted is
        // unchanged by its admission.
        ...(analysis.keyedRegions.length === 0
          ? {}
          : {
              keyedRegions: analysis.keyedRegions.map((region) => ({
                id: region.id,
                container: region.container,
                item: region.item,
                each: region.each,
                keyAttribute: region.keyAttribute,
                keyPath: region.keyPath,
                itemTemplate: region.itemTemplate,
                captures: region.captures,
                bindings: region.itemBindings.map((binding) => ({
                  id: binding.id,
                  kind: binding.kind,
                  locator: binding.locator,
                  captures: binding.captures,
                })),
                wiring: region.itemWiring,
              })),
            }),
        // And again: a component that addresses nothing writes no
        // `claimedChildren` key, so every manifest emitted before addressing
        // existed is unchanged by its arrival.
        //
        // THE MANIFEST IS THE ONLY PLACE THIS LIVES, and that is a decision
        // rather than an accident. `structure.js` is the EAGER path — it is
        // imported by the page's static glob and its bytes are on the wire at
        // first paint — and nothing that runs on that path reads a claimed
        // child: the resume side finds a nested mount by walking
        // `[data-component]`, exactly as it finds a root one, so the address
        // recorded here is BUILD-TIME metadata and nothing else. The build-side
        // readers — the verbatim gate, the page rewriter and the group stage —
        // all run beside the build, where reading a JSON file costs nothing a
        // visitor pays for. An address that no runtime asks for is an address
        // that does not belong in a shipped module.
        ...(analysis.claimedChildren.length === 0
          ? {}
          : { claimedChildren: analysis.claimedChildren }),
        handlers: analysis.handlers.map((handler) => ({
          id: handler.id,
          event: handler.event,
          locator: handler.locator,
          module: handler.module,
          captures: handler.captures,
        })),
        wiring: analysis.wiring,
        files,
      },
      null,
      2,
    ) + "\n"
  );
}

/** Everything currently on disk under `dir`, artifact-relative. pathe keeps the
 * separators posix on every platform, which is what artifact keys assume. */
function listFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  const walk = (current: string) => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) walk(full);
      else out.push(relative(dir, full));
    }
  };
  walk(dir);
  return out.sort();
}

/**
 * Artifacts are keyed by `(module path, local component name)` and the manifest
 * records that pair, so a directory can say who owns it. Module-local
 * components are emittable, so one directory name is reachable from two pairs —
 * which is a build error here rather than a silent overwrite.
 */
function assertNotAnotherComponents(analysis: ProvableAnalysis, dir: string): void {
  const manifest = join(dir, "manifest.json");
  if (!existsSync(manifest)) return;

  let owner: { component?: unknown; module?: unknown };
  try {
    owner = JSON.parse(readFileSync(manifest, "utf8"));
  } catch {
    return; // Unreadable leftovers are pruned below, not treated as a claim.
  }

  if (typeof owner.component !== "string" || typeof owner.module !== "string") return;
  if (owner.component === analysis.component && owner.module === analysis.module) return;

  throw new Error(
    `artifact key collision at ${dir}: already holds ${owner.module} -> ${owner.component}, ` +
      `refusing to overwrite it with ${analysis.module} -> ${analysis.component}`,
  );
}

export function emit(analysis: ProvableAnalysis, dir: string): EmitResult {
  assertNotAnotherComponents(analysis, dir);


  // Rendered in memory first, then written over whatever is already there.
  // Deleting the directory up front is simpler but opens a window where the
  // artifacts do not exist, and these files are meant to be imported — possibly
  // by a test run emitting them from another worker at the same instant.
  const contents = new Map<string, string>([
    ["template.js", emitTemplate(analysis)],
    ["structure.js", emitStructure(analysis)],
    ["wiring.js", emitWiring(analysis)],
  ]);
  for (let i = 0; i < analysis.handlers.length; i++) {
    contents.set(`handlers/${analysis.handlers[i].id}.js`, emitHandler(analysis, i));
  }

  const artifacts = [...contents.keys()].sort();
  contents.set("manifest.json", emitManifest(analysis, artifacts));

  mkdirSync(join(dir, "handlers"), { recursive: true });

  // Prune anything left over from an earlier shape of the analysis.
  for (const stale of listFiles(dir)) {
    if (!contents.has(stale)) rmSync(join(dir, ...stale.split("/")), { force: true });
  }

  const files = [...contents.keys()].sort();
  for (const file of files) {
    writeFileSync(join(dir, ...file.split("/")), contents.get(file)!, "utf8");
  }

  return { dir, files };
}
