// Generated by the solid-resumability comptime pass. Do not edit.
// Source: app/src/fixtures/KeyedRoster.tsx -> RosterList

/**
 * One event handler, extracted whole from the component and factored over an
 * explicit capture-slot manifest. The function body below is the author's
 * own source, printed back out by yuku-codegen; nothing was injected into the
 * component to make this possible.
 */
export const id = "s0";
export const event = "click";
export const locator = "/1";

/** The slots `create` needs, and the cell each one is bound to. */
export const captures = [
  { name: "drop", kind: "action", store: "s0", path: [1,"drop"] },
  { name: "member", kind: "region-item", region: "k0" },
  { name: "setLast", cell: "c0", access: "write" },
];

export function create({ drop, member, setLast }) {
  return () => setLast(drop(member.id));
}
