// Generated by the solid-resumability comptime pass. Do not edit.
// Source: src/fixtures/CounterA.tsx -> CounterA

/**
 * One event handler, extracted whole from the component and factored over an
 * explicit capture-slot manifest. The function body below is the author's
 * own source, printed back out by yuku-codegen; nothing was injected into the
 * component to make this possible.
 */
export const id = "s1";
export const event = "click";
export const locator = "/2";

/** The slots `create` needs, and the cell each one is bound to. */
export const captures = [
  { name: "count", cell: "c0", access: "read" },
  { name: "setCount", cell: "c0", access: "write" },
];

export function create({ count, setCount }) {
  return () => setCount(count() - 1);
}
